import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="tw-container tw-mx-auto">
        <h1 className="tw-text-2xl tw-text-center tw-mb-8">Hello, world!</h1>
      </main>
    </div>
  );
}
